### ISSUE TITLE
How to train the model

### ISSUE THREAD

**Issue by tangxiangru** [raylin1000/drop_bert#2]
Need I run Metrics.ipynb before I run Run.ipynb?

But I meet the bug `ModuleNotFoundError: No module named 'allennlp.training.metrics.drop_em_and_f1'`

**Comment by raylin1000** [comment]
Have you installed `allennlp` in the environment where you're running the notebook? If not you'll need to do that by running `pip install allennlp==0.8.3`. I'll add some more details for how we set up our environment in the README.

Edit: Oh also, since `Run.ipynb` uses the allennlp command line tools, you'll want to make sure those are properly installed before you run that notebook. The notebooks should all be able to be run independently once the proper libraries have been installed.
